"""
Django settings for courtvision project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-courtvision-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third party apps
    'django_bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'corsheaders',
    'widget_tweaks',
    'taggit',

    # Local apps
    'legal_research',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'courtvision.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'courtvision.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For production PostgreSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Languages supported
LANGUAGES = [
    ('en', 'English'),
    ('hi', 'हिन्दी (Hindi)'),
    ('ta', 'தமிழ் (Tamil)'),
    ('te', 'తెలుగు (Telugu)'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Bootstrap 5 Configuration
BOOTSTRAP5 = {
    'fqpn': 'bootstrap5/bootstrap5.min.css',
    'theme_url': 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css',
    'javascript_url': 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js',
}

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration (for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# Message Tags
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'legal_research': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# AI/ML Infrastructure Settings
AI_SETTINGS = {
    # OpenAI Configuration
    'OPENAI_API_KEY': config('OPENAI_API_KEY', default=''),
    'OPENAI_MODEL': config('OPENAI_MODEL', default='gpt-4-turbo-preview'),
    'OPENAI_MAX_TOKENS': config('OPENAI_MAX_TOKENS', default=2000, cast=int),
    'OPENAI_TEMPERATURE': config('OPENAI_TEMPERATURE', default=0.1, cast=float),

    # Search and Vector Database
    'ELASTICSEARCH_HOST': config('ELASTICSEARCH_HOST', default='localhost:9200'),
    'ELASTICSEARCH_INDEX_PREFIX': config('ELASTICSEARCH_INDEX_PREFIX', default='legal_cases'),
    'VECTOR_DIMENSION': config('VECTOR_DIMENSION', default=384, cast=int),
    'SEARCH_RESULTS_LIMIT': config('SEARCH_RESULTS_LIMIT', default=50, cast=int),

    # Caching Configuration
    'AI_CACHE_TIMEOUT': config('AI_CACHE_TIMEOUT', default=3600, cast=int),  # 1 hour
    'SEARCH_CACHE_TIMEOUT': config('SEARCH_CACHE_TIMEOUT', default=1800, cast=int),  # 30 minutes
    'TRANSLATION_CACHE_TIMEOUT': config('TRANSLATION_CACHE_TIMEOUT', default=86400, cast=int),  # 24 hours

    # Model Storage
    'MODEL_STORAGE_PATH': config('MODEL_STORAGE_PATH', default=BASE_DIR / 'models'),
    'MODEL_AUTO_UPDATE': config('MODEL_AUTO_UPDATE', default=True, cast=bool),
    'MODEL_UPDATE_INTERVAL': config('MODEL_UPDATE_INTERVAL', default=7, cast=int),  # days

    # Ethical AI Settings
    'AI_AUDIT_RETENTION_DAYS': config('AI_AUDIT_RETENTION_DAYS', default=2555, cast=int),  # 7 years
    'BIAS_DETECTION_ENABLED': config('BIAS_DETECTION_ENABLED', default=True, cast=bool),
    'HUMAN_REVIEW_THRESHOLD': config('HUMAN_REVIEW_THRESHOLD', default=0.6, cast=float),
    'ETHICAL_COMPLIANCE_THRESHOLD': config('ETHICAL_COMPLIANCE_THRESHOLD', default=0.8, cast=float),

    # Data Processing
    'MAX_DOCUMENT_SIZE': config('MAX_DOCUMENT_SIZE', default=50 * 1024 * 1024, cast=int),  # 50MB
    'BATCH_PROCESSING_SIZE': config('BATCH_PROCESSING_SIZE', default=10, cast=int),
    'ASYNC_PROCESSING_ENABLED': config('ASYNC_PROCESSING_ENABLED', default=True, cast=bool),

    # Language Support
    'SUPPORTED_LANGUAGES': config('SUPPORTED_LANGUAGES', default='en,hi,ta,te', cast=lambda v: [s.strip() for s in v.split(',')]),
    'DEFAULT_LANGUAGE': config('DEFAULT_LANGUAGE', default='en'),
    'TRANSLATION_ENABLED': config('TRANSLATION_ENABLED', default=True, cast=bool),

    # Data Source Configuration
    'DATA_IMPORT_ENABLED': config('DATA_IMPORT_ENABLED', default=True, cast=bool),
    'DATA_IMPORT_SCHEDULE': config('DATA_IMPORT_SCHEDULE', default='0 2 * * *'),  # Daily at 2 AM
    'MAX_IMPORT_BATCH_SIZE': config('MAX_IMPORT_BATCH_SIZE', default=100, cast=int),
    'DATA_SOURCE_TIMEOUT': config('DATA_SOURCE_TIMEOUT', default=30, cast=int),

    # Performance Settings
    'AI_REQUEST_TIMEOUT': config('AI_REQUEST_TIMEOUT', default=30, cast=int),
    'MAX_CONCURRENT_AI_REQUESTS': config('MAX_CONCURRENT_AI_REQUESTS', default=5, cast=int),
    'ENABLE_AI_RATE_LIMITING': config('ENABLE_AI_RATE_LIMITING', default=True, cast=bool),
    'AI_RATE_LIMIT_REQUESTS_PER_HOUR': config('AI_RATE_LIMIT_REQUESTS_PER_HOUR', default=1000, cast=int),
}

# Redis Configuration for Caching and Celery
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

# Try to detect if Redis is available; if not, fall back to safe local defaults for development.
USE_REDIS = True
try:
    # Parse host and port from REDIS_URL (simple parsing)
    from urllib.parse import urlparse
    parsed = urlparse(REDIS_URL)
    redis_host = parsed.hostname or 'localhost'
    redis_port = parsed.port or 6379
    import socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.5)
    try:
        sock.connect((redis_host, redis_port))
        sock.close()
    except Exception:
        USE_REDIS = False
except Exception:
    USE_REDIS = False

if USE_REDIS:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        },
        'ai_cache': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL + '/1',
            'TIMEOUT': AI_SETTINGS['AI_CACHE_TIMEOUT'],
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        },
        'search_cache': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL + '/2',
            'TIMEOUT': AI_SETTINGS['SEARCH_CACHE_TIMEOUT'],
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

    # Celery Configuration for Background Tasks (using Redis)
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
else:
    # Fallback to local in-memory cache and memory-based Celery broker for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        },
        'ai_cache': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ai-cache',
            'TIMEOUT': AI_SETTINGS['AI_CACHE_TIMEOUT'],
        },
        'search_cache': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'search-cache',
            'TIMEOUT': AI_SETTINGS['SEARCH_CACHE_TIMEOUT'],
        }
    }

    # Use in-memory broker/backends for Celery in dev mode to avoid connection errors
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache'
    CELERY_CACHE_BACKEND = 'default'

    # Also ensure session engine will not rely on Redis
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

    # Log the fallback so developers are aware
    import logging
    logging.getLogger('legal_research').warning('Redis not available; falling back to LocMemCache and in-memory Celery broker for development.')

# Celery general settings (remain valid for either backend)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Configuration for Scheduled Tasks
CELERY_BEAT_SCHEDULE = {
    'data-import-daily': {
        'task': 'legal_research.tasks.scheduled_data_import',
        'schedule': crontab(minute=0, hour=2),  # Daily at 2 AM
    },
    'model-training-weekly': {
        'task': 'legal_research.tasks.train_ml_models',
        'schedule': crontab(minute=0, hour=3, day_of_week=1),  # Weekly on Monday at 3 AM
    },
    'cache-cleanup-daily': {
        'task': 'legal_research.tasks.cleanup_old_cache',
        'schedule': crontab(minute=0, hour=4),  # Daily at 4 AM
    },
    'audit-log-cleanup-monthly': {
        'task': 'legal_research.tasks.cleanup_old_audit_logs',
        'schedule': crontab(minute=0, hour=5, day_of_month=1),  # Monthly on 1st at 5 AM
    },
}

# Session Configuration for AI Features
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = AI_SETTINGS['MAX_DOCUMENT_SIZE']
DATA_UPLOAD_MAX_MEMORY_SIZE = AI_SETTINGS['MAX_DOCUMENT_SIZE']

# Security Settings for AI
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# API Rate Limiting
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

# Monitoring and Analytics
MONITORING_ENABLED = config('MONITORING_ENABLED', default=True, cast=bool)
ANALYTICS_ENABLED = config('ANALYTICS_ENABLED', default=True, cast=bool)
PERFORMANCE_MONITORING = config('PERFORMANCE_MONITORING', default=True, cast=bool)

# Create necessary directories
os.makedirs(AI_SETTINGS['MODEL_STORAGE_PATH'], exist_ok=True)
os.makedirs(BASE_DIR / 'logs' / 'ai', exist_ok=True)
os.makedirs(BASE_DIR / 'logs' / 'audit', exist_ok=True)