# Generated by Django 5.1.3 on 2025-11-06 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Court Name')),
                ('jurisdiction', models.CharField(max_length=200, verbose_name='Jurisdiction')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Court Code')),
                ('established_date', models.DateField(verbose_name='Established Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'High Court',
                'verbose_name_plural': 'High Courts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Case Title')),
                ('citation', models.CharField(max_length=200, verbose_name='Citation')),
                ('bench', models.CharField(blank=True, max_length=200, verbose_name='Bench')),
                ('judgment_date', models.DateField(verbose_name='Judgment Date')),
                ('decision_date', models.DateField(verbose_name='Decision Date')),
                ('petitioners', models.TextField(verbose_name='Petitioners')),
                ('respondents', models.TextField(verbose_name='Respondents')),
                ('case_text', models.TextField(verbose_name='Full Case Text')),
                ('headnotes', models.TextField(blank=True, verbose_name='Headnotes')),
                ('ai_summary', models.JSONField(default=dict, verbose_name='AI Summary')),
                ('extracted_principles', models.JSONField(default=list, verbose_name='Extracted Legal Principles')),
                ('statutes_cited', models.JSONField(default=list, verbose_name='Statutes Cited')),
                ('precedents_cited', models.JSONField(default=list, verbose_name='Precedents Cited')),
                ('case_type', models.CharField(choices=[('judgment', 'Judgment'), ('order', 'Order'), ('interim', 'Interim Order'), ('appeal', 'Appeal'), ('revision', 'Revision')], default='judgment', max_length=100, verbose_name='Case Type')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='Relevance Score')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_research.highcourt', verbose_name='Court')),
                ('tags', models.ManyToManyField(blank=True, to='legal_research.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-judgment_date'],
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Note Text')),
                ('is_private', models.BooleanField(default=True, verbose_name='Private')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Starred')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_research.case', verbose_name='Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Note',
                'verbose_name_plural': 'User Notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=10, verbose_name='Default Language')),
                ('notification_settings', models.JSONField(default=dict, verbose_name='Notification Settings')),
                ('preferences', models.JSONField(default=dict, verbose_name='User Preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('high_court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_research.highcourt', verbose_name='High Court')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Suit Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('suit_type', models.CharField(choices=[('civil', 'Civil Suit'), ('criminal', 'Criminal Case'), ('commercial', 'Commercial Dispute'), ('tax', 'Tax Matter'), ('constitutional', 'Constitutional Matter'), ('other', 'Other')], max_length=100, verbose_name='Suit Type')),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_users', models.ManyToManyField(related_name='suit_assignments', to='legal_research.userprofile', verbose_name='Assigned Users')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_research.userprofile', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Suit',
                'verbose_name_plural': 'Suits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_type', models.CharField(choices=[('search_trends', 'Search Trends'), ('case_views', 'Case Views'), ('user_activity', 'User Activity'), ('system_usage', 'System Usage'), ('predictions', 'Predictions')], max_length=50, verbose_name='Analytics Type')),
                ('data', models.JSONField(verbose_name='Analytics Data')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Analytics Data',
                'verbose_name_plural': 'Analytics Data',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['user', 'analytics_type', 'period_end'], name='legal_resea_user_id_d98e93_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(default='General', max_length=100, verbose_name='Folder')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='User Tags')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Saved At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_research.case', verbose_name='Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Case',
                'verbose_name_plural': 'Saved Cases',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'case')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Search Query')),
                ('filters', models.JSONField(default=dict, verbose_name='Search Filters')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Results Count')),
                ('search_time', models.FloatField(default=0.0, verbose_name='Search Time (seconds)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Search Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='legal_resea_user_id_e52595_idx'), models.Index(fields=['timestamp'], name='legal_resea_timesta_5d1c31_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_emphasis', models.JSONField(default=dict, verbose_name='Jurisdiction Emphasis')),
                ('language_preferences', models.JSONField(default=list, verbose_name='Language Preferences')),
                ('precedent_statute_weight', models.FloatField(default=0.5, verbose_name='Precedent vs Statute Weight')),
                ('time_period_focus', models.CharField(choices=[('recent', 'Recent Cases (Last 5 years)'), ('medium', 'Medium Period (Last 10 years)'), ('historical', 'Historical (All Time)'), ('custom', 'Custom Range')], default='recent', max_length=50, verbose_name='Time Period Focus')),
                ('analysis_focus_areas', models.JSONField(default=list, verbose_name='Analysis Focus Areas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_research.suit', verbose_name='Suit')),
            ],
            options={
                'verbose_name': 'Customization',
                'verbose_name_plural': 'Customizations',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'suit')},
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['court', 'judgment_date'], name='legal_resea_court_i_1fac02_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_type'], name='legal_resea_case_ty_437f43_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['relevance_score'], name='legal_resea_relevan_635d41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'case')},
        ),
    ]
