# Generated by Django 5.1.3 on 2025-11-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI Confidence Score'),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_error_log',
            field=models.TextField(blank=True, verbose_name='AI Error Log'),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_model_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='AI Model Version'),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI Processed At'),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='AI Processing Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='audit_log_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Audit Log ID'),
        ),
        migrations.AddField(
            model_name='case',
            name='bias_detected',
            field=models.BooleanField(default=False, verbose_name='Bias Detected'),
        ),
        migrations.AddField(
            model_name='case',
            name='data_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Imported At'),
        ),
        migrations.AddField(
            model_name='case',
            name='data_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Data Quality Score'),
        ),
        migrations.AddField(
            model_name='case',
            name='data_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='case',
            name='embedding_vector',
            field=models.JSONField(default=list, verbose_name='Embedding Vector'),
        ),
        migrations.AddField(
            model_name='case',
            name='ethical_compliance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Ethical Compliance Score'),
        ),
        migrations.AddField(
            model_name='case',
            name='human_review_required',
            field=models.BooleanField(default=False, verbose_name='Human Review Required'),
        ),
        migrations.AddField(
            model_name='case',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Indexed At'),
        ),
        migrations.AddField(
            model_name='case',
            name='last_translated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Translated At'),
        ),
        migrations.AddField(
            model_name='case',
            name='predicted_outcome',
            field=models.JSONField(default=dict, verbose_name='Predicted Outcome'),
        ),
        migrations.AddField(
            model_name='case',
            name='prediction_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Prediction Accuracy'),
        ),
        migrations.AddField(
            model_name='case',
            name='prediction_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Prediction Confidence'),
        ),
        migrations.AddField(
            model_name='case',
            name='prediction_made_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prediction Made At'),
        ),
        migrations.AddField(
            model_name='case',
            name='search_vector',
            field=models.TextField(blank=True, verbose_name='Search Vector'),
        ),
        migrations.AddField(
            model_name='case',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='case',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='case',
            name='supported_languages',
            field=models.JSONField(default=list, verbose_name='Supported Languages'),
        ),
        migrations.AddField(
            model_name='case',
            name='translated_content',
            field=models.JSONField(default=dict, verbose_name='Translated Content'),
        ),
    ]
